### PR TITLE
Minor documentation updates - spelling and formatting

### PR DESCRIPTION
**Pull request by pete-thompson**
Starting to integrate the changes from Veer's fork. This is the first easy one :)

### CODE REVIEW

**Comment by pete-thompson** [comment]
Odd that the travis build is failing. I've not changed any code, just the README.MD file - so presumably there's a problem with the master branch?

**Comment by pete-thompson** [comment]
Makes no sense! NPM INSTALL is working clean for me locally, but failed on Travis. The problem is something to do with the recent upgrade of grunt to 1.0 and conflicts between the dependencies in various modules we're using.

**Comment by cianclarke** [comment]
Well then, that was an unpleasant 20 mins of screwing around with NPM!
Indeed, a major version bump of grunt seems to have broken lots of things. 
I've fixed this in https://github.com/cianclarke/sharepointer/pull/11, and the build passed just fine. Can you rebase master back into this branch (or merge if you're not sure how, I don't mind) and I can get this merged? 
Cheers!

**Comment by pete-thompson** [comment]
Indeed - much "fun" caused by the grunt update :)
I tried rebase, got myself confused, figured I was safer with a merge! I'll need to do something similar with my other branches, so might try rebase again or might end up giving up!

**Pull request merged**
